# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: grski's
author: Olaf 'grski' Górski
email: olafgorski@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog o rzeczach różnych, głównie z programowaniem i IT związanych okiem nastoletniego ucznia,
  który najchętniej pisze o tematach spokrewnionych z Pythonem, Django i Linuxem.<br/>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grski.pl" # the base hostname & protocol for your site
github_username: grski 

# Build settings
markdown: kramdown
